defaults:
  - main
  - _self_

default_fillers:
  partition: '<haicore_partition>' # haicore_partition is defined in global_config.yaml
  job_name: "haicore"
  time: "72:00:00"
  cpus: "152"
  mem: "501600mb"
  gres: "gpu:full:4"

NO_gpus: 4
max_tasks: null