defaults:
  - main
  - _self_

default_fillers:
  partition: '<haicore_partition>' # haicore_partition is defined in global_config.yaml
  job_name: "haicore"
  time: "72:00:00"
  cpus: "19"
  mem: "62700mb"
  gres: "gpu:full:1"

NO_gpus: 1
max_tasks: null