preamble: |
  #!/bin/bash
  #SBATCH --ntasks=1
  #SBATCH --cpus-per-task=<cpus>
  #SBATCH --gres=gpu:1
  #SBATCH --mem=<mem>
  #SBATCH --job-name=<job_name>
  #SBATCH --time=<time>
  #SBATCH --partition=gpu
  <additional_sbatch_configs>

  source ${HOME}/.bashrc
  export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
  conda activate <env>

defaults:
  job_name: "nano"
  env: "annealed_bg"
  cpus: "16"
  mem: "64000mb"
  time: "50-24:00:00"
  additional_sbatch_configs: ""