preamble: |
  #!/bin/bash
  #SBATCH --ntasks=1
  #SBATCH --cpus-per-task=<cpus>
  #SBATCH --gres=gpu:1
  #SBATCH --mem=<mem>
  #SBATCH --job-name=<job_name>
  #SBATCH --time=<time>
  #SBATCH --partition=accelerated
  source ${HOME}/.bashrc
  export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
  conda activate <env>

defaults:
  job_name: "horeka"
  env: "annealed_bg"
  cpus: "19"
  mem: "125000mb"
  time: "2-00:00:00"