preamble: |
  #!/bin/bash
  #SBATCH --ntasks=1
  #SBATCH --cpus-per-task=19
  #SBATCH --gres=gpu:1
  #SBATCH --mem=125000mb
  #SBATCH --job-name=<job_name>
  #SBATCH --time=2-00:00:00
  #SBATCH --partition=accelerated
  source ${HOME}/.bashrc
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/miniforge3/lib
  conda activate <env>

defaults:
  job_name: "horeka"
  env: "annealed_bg"